# postgres with keycloak
version: '3.9'
services:
  postges:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-auth
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: Password123
      KC_HOSTNAME_URL: https://sso.malker.xyz
      KC_HOSTNAME_STRICT_HTTPS: "true"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_PROXY: edge
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Password123
      KEYCLOAK_FRONTEND_URL: "https://sso.malker.xyz/auth"
    ports:
      - 8443:8443
      - 8080:8080
    networks:
      - keycloak-auth
    depends_on:
      - postges
    command: start
volumes:
  postgres_data:
  driver: local
networks:
  keycloak-auth:
    driver: bridge
